spring:
  profiles:
    active: TO_BE_SET
  swagger-ui:
    url: /v3/api-docs.yaml
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    # TTL for cache entries in milliseconds (e.g., 10 minutes)
    time-to-live: 600000
# Redis cache configuration for @Cacheable support. TTL is set to 10 minutes for price queries.
